name: Weekly update weekchart
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * mon'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  weekly-update-weekchart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: 20
    - name: Install package
      run: npm install
    - name: Update chart
      env:
        BIRTHDAY: ${{ secrets.BIRTHDAY }}
      run: node src/index.js weekchart:update
    - name: Update README.md
      run: node src/index.js readme:update
      env:
        BIRTHDAY: ${{ secrets.BIRTHDAY }}
        GIT_USERNAME: $GIT_USERNAME
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "[AUTO] update live week to README.md"
          git push
